language: java
install: mvn clean install
jdk:
  - oraclejdk8
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: develop