serverID: "SQ001"
edit: true
SheepQuest:
    Arena:
        radio: 2
        Spawn:
            rojo: world%200.0%70.0%0.0%0.0%0.0
            amarillo: world%210.0%70.0%0.0%0.0%0.0
            verde: world%220.0%70.0%0.0%0.0%0.0
            azul: world%230.0%70.0%0.0%0.0%0.0
