TeamTntWars:
    Arena:
        usersMin: 5
        usersMax: 20
        areaBorder1: world%0.0%70.0%0.0%0.0%0.0
        areaBorder2: world%0.0%70.0%0.0%0.0%0.0
        lobby: world%0.0%70.0%0.0%0.0%0.0
        islas:
            1:
                borderPos1: world%0.0%70.0%0.0%0.0%0.0
                borderPos2: world%0.0%70.0%0.0%0.0%0.0
